# Generated by Django 3.0.2 on 2020-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
