# Generated by Django 3.0.2 on 2020-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200909_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=200)),
                ('wnumber', models.IntegerField()),
                ('assembly', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('Tenure', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=225)),
                ('bgroup', models.CharField(max_length=225)),
                ('education', models.CharField(max_length=225)),
                ('pyear', models.IntegerField()),
                ('occupation', models.CharField(max_length=225)),
                ('anumber', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
