# Generated by Django 3.0.2 on 2020-08-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200824_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='add',
        ),
    ]
