# Generated by Django 3.0.2 on 2020-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200825_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=200)),
                ('wnumber', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.IntegerField()),
                ('position', models.CharField(max_length=225)),
                ('bgroup', models.CharField(max_length=225)),
                ('education', models.CharField(max_length=225)),
                ('pyear', models.IntegerField()),
                ('occupation', models.CharField(max_length=225)),
                ('anumber', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
