# Generated by Django 3.0.2 on 2020-08-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200826_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Info',
        ),
    ]
