# Generated by Django 3.0.2 on 2020-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200826_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Bio',
        ),
    ]
