# Generated by Django 3.0.2 on 2020-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200826_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='Tenure',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='assembly',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='post',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
